site_name: Recyclerview Adapter Helper
site_description: Recyclerview Adapter Helper框架文档
repo_url: https://github.com/knightwood/RecyclerviewNeko

site_author: knightwood
copyright: Copyright &copy; 2018 - 2024 knightwood
repo_name: GitHub
docs_dir: 'docs'

theme:
  # name: bootstrap386
  name: material

# markdown_extensions:
#   - toc:
#       permalink: true
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tabbed:
#       alternate_style: true
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - attr_list
#   - def_list
#   - md_in_html
#   - admonition
#   - pymdownx.highlight
#   - pymdownx.details
#   - pymdownx.caret
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.tilde
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
  - 简单使用: index.md
  - 多种Viewholder: multi-type.md
  - 点击事件: click.md
  - 拖拽与侧滑: drag.md
  - 列表动画: animation.md
  - ViewBinding: view-binding.md
  # - 更新数据: refresh-data.md
  - 刷新预加载: header_footer.md
  - 缺省页: state.md
  - concatAdapter.md
  - listAdapter.md
  - paging3.md
